### ISSUE TITLE
R0 definition should not be daily but lifespan calculated

### ISSUE THREAD

**Issue by AshtonIzmev** [AshtonIzmev/covid-19-pandemic-simulation#13]
I was thinking about the plots of R0 and it did strike me that they were too low. We calculated basically daily R0 but the definition should apply on the lifespan of individuals. It will make it harder or we need to track a NC per individual I guess.
Will think about it :/

**Comment by Abdelmouise** [comment]
yes i understand what you're saying,  but just a question, in this case the R0 is not a value that changes over time? and if you want to calculate the R0, is it necessary to take the average number of people contaminated by each infected person? or just the average of contaminated person infected by the people who were infected at the start of the pandemic?
because people infected at the end of the simulation they will not have time to infect others, and suddenly it can drop R0

**Comment by Abdelmouise** [comment]
I think that what we calculated was "Effective reproductive number" not the "Basic  reproductive number"

**Comment by AshtonIzmev** [comment]
I guess a moving average R0 calculated on "have been" contagious people will do the job. I  think it is nice to keep an "average" R0 day by day to see its evolution.

**Comment by AshtonIzmev** [comment]
Submitted a new 14-days sliding R0 definition !
